# Generated by Django 5.2 on 2025-05-19 04:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_company_user_drug_user_expiry_user_historysale_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='contact_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_contact', message='Contact number must be exactly 10 digits.', regex='^\\d{10}$')]),
        ),
    ]
